/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author DELL
 */
public class CreateJPanel extends javax.swing.JPanel {
    
    JPanel WorkCard;
    PersonDirectory personDirectory;
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(JPanel WorkCard,PersonDirectory personDirectory) {
        initComponents();
        this.WorkCard=WorkCard;
        this.personDirectory=personDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createLabel = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        firstnamelbl = new javax.swing.JLabel();
        firstnametxt = new javax.swing.JTextField();
        lastnametxt = new javax.swing.JTextField();
        lastnamelbl = new javax.swing.JLabel();
        ssnlbl = new javax.swing.JLabel();
        ssntxt = new javax.swing.JTextField();
        gendertxt = new javax.swing.JTextField();
        genderlbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        preaddlbl = new javax.swing.JLabel();
        add1lbl = new javax.swing.JLabel();
        add1txt = new javax.swing.JTextField();
        statetxt = new javax.swing.JTextField();
        statelbl = new javax.swing.JLabel();
        housenolbl = new javax.swing.JLabel();
        housenotxt = new javax.swing.JTextField();
        zipcodetxt = new javax.swing.JTextField();
        zipcodelbl = new javax.swing.JLabel();
        mobilenotxt = new javax.swing.JTextField();
        mobilenolbl = new javax.swing.JLabel();
        citytxt = new javax.swing.JTextField();
        landmarklbl = new javax.swing.JLabel();
        landmarktxt = new javax.swing.JTextField();
        citylbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        peraddlbl = new javax.swing.JLabel();
        add1lbl1 = new javax.swing.JLabel();
        mobilenotxt1 = new javax.swing.JTextField();
        statetxt1 = new javax.swing.JTextField();
        zipcodelbl1 = new javax.swing.JLabel();
        mobilenolbl1 = new javax.swing.JLabel();
        zipcodetxt1 = new javax.swing.JTextField();
        statelbl1 = new javax.swing.JLabel();
        add1txt1 = new javax.swing.JTextField();
        housenotxt1 = new javax.swing.JTextField();
        citytxt1 = new javax.swing.JTextField();
        citylbl1 = new javax.swing.JLabel();
        housenolbl1 = new javax.swing.JLabel();
        landmarktxt1 = new javax.swing.JTextField();
        landmarklbl1 = new javax.swing.JLabel();
        createbtn = new javax.swing.JButton();
        salarylbl = new javax.swing.JLabel();
        salarytxt = new javax.swing.JTextField();
        employeeidlbl = new javax.swing.JLabel();
        employeeidtxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 204, 255));

        createLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        createLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createLabel.setText("Create Profile");

        backbtn.setText("<<< Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        firstnamelbl.setText("First Name");

        lastnamelbl.setText("Last Name");

        ssnlbl.setText("SSN");

        genderlbl.setText("Gender");

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));

        preaddlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        preaddlbl.setText("Present Address");

        add1lbl.setText("Address");

        statelbl.setText("State");

        housenolbl.setText("House No.");

        zipcodelbl.setText("ZipCode");

        mobilenolbl.setText("Mobile No.");

        landmarklbl.setText("Landmark");

        citylbl.setText("City");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(add1lbl)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(preaddlbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(add1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(housenolbl)
                            .addComponent(statelbl)
                            .addComponent(landmarklbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(statetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zipcodelbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(landmarktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mobilenolbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(housenotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(citylbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(citytxt)
                            .addComponent(zipcodetxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobilenotxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {citytxt, housenotxt, mobilenotxt, zipcodetxt});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(preaddlbl)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add1lbl)
                    .addComponent(add1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housenolbl)
                    .addComponent(housenotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(citytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(citylbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statelbl)
                    .addComponent(statetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcodelbl)
                    .addComponent(zipcodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(landmarklbl)
                    .addComponent(landmarktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobilenolbl)
                    .addComponent(mobilenotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));

        peraddlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        peraddlbl.setText("Permanent Address");

        add1lbl1.setText("Address 1");

        statetxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statetxt1ActionPerformed(evt);
            }
        });

        zipcodelbl1.setText("ZipCode");

        mobilenolbl1.setText("Mobile No.");

        statelbl1.setText("State");

        citylbl1.setText("City");

        housenolbl1.setText("House No.");

        landmarklbl1.setText("Landmark");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(peraddlbl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(add1lbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(add1txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(housenolbl1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(housenotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(landmarklbl1)
                                        .addGap(18, 18, 18)
                                        .addComponent(landmarktxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(statelbl1)
                                        .addGap(42, 42, 42)
                                        .addComponent(statetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(zipcodelbl1)
                                            .addComponent(mobilenolbl1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(mobilenotxt1)
                                            .addComponent(zipcodetxt1)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(citylbl1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(citytxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(11, 11, 11))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {landmarktxt1, statetxt1});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {citytxt1, mobilenotxt1, zipcodetxt1});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(peraddlbl)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add1lbl1)
                    .addComponent(add1txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housenolbl1)
                    .addComponent(housenotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(citytxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(citylbl1))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statelbl1)
                    .addComponent(zipcodelbl1)
                    .addComponent(zipcodetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilenotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobilenolbl1)
                    .addComponent(landmarklbl1)
                    .addComponent(landmarktxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        createbtn.setText("Create");
        createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtnActionPerformed(evt);
            }
        });

        salarylbl.setText("Salary");

        salarytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarytxtActionPerformed(evt);
            }
        });

        employeeidlbl.setText("Employee Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(backbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(createbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(firstnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(firstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lastnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lastnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(genderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(employeeidlbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(gendertxt, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                            .addComponent(employeeidtxt))))))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salarylbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ssntxt, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(salarytxt))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createLabel))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnamelbl)
                    .addComponent(firstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnamelbl)
                    .addComponent(lastnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderlbl)
                    .addComponent(gendertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssnlbl)
                    .addComponent(ssntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salarytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salarylbl)
                            .addComponent(employeeidlbl)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeeidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        WorkCard.remove(this);
        CardLayout layout = (CardLayout) WorkCard.getLayout();
        layout.previous(WorkCard);
        
    }//GEN-LAST:event_backbtnActionPerformed

    private void createbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtnActionPerformed
        // TODO add your handling code here:
        
        if (!validateInputFields()) {
            return; 
        }
        
        String firstname=firstnametxt.getText();
         String lastname=lastnametxt.getText();
         long ssn=Long.parseLong(ssntxt.getText());
         String gender=gendertxt.getText();
         float salary = Float.parseFloat(salarytxt.getText());
         int employeeid = Integer.parseInt(employeeidtxt.getText());
         

        String stadd1 = add1txt.getText();
        String state = statetxt.getText();
        String city = citytxt.getText();
        String landmark = landmarktxt.getText();
        int houseno = Integer.parseInt(housenotxt.getText());
        int zipcode = Integer.parseInt(zipcodetxt.getText());
        long mobileno = Long.parseLong(mobilenotxt.getText());
        
        Address presentAddress = new Address(stadd1,state,city,landmark,houseno,zipcode,mobileno);
        
        String pstadd1 = add1txt1.getText();
        String pstate = statetxt1.getText();
        String pcity = citytxt1.getText();
        String plandmark = landmarktxt1.getText();
        int phouseno = Integer.parseInt(housenotxt1.getText());
        int pzipcode = Integer.parseInt(zipcodetxt1.getText());
        long pmobileno = Long.parseLong(mobilenotxt1.getText());
        
        Address permanentAddress = new Address(pstadd1,pstate,pcity,plandmark,phouseno,pzipcode,pmobileno);
        
        Person p=personDirectory.addAccount();
        p.setFirstName(firstname);
        p.setLastName(lastname);
        p.setSsn(ssn);
        p.setGender(gender);
        p.setSalary(salary);
        p.setEmployeeid(employeeid);
        p.setPrehomeAdd(presentAddress);
        p.setPerhomeAdd(permanentAddress);

        JOptionPane.showMessageDialog(this, "Account Sucessfully Created", "Sucess", JOptionPane.INFORMATION_MESSAGE);
        firstnametxt.setText("");
        lastnametxt.setText("");
        gendertxt.setText("");
        ssntxt.setText("");
        salarytxt.setText("");
        employeeidtxt.setText("");
        add1txt.setText("");
        housenotxt.setText("");
        citytxt.setText("");
        statetxt.setText("");
        zipcodetxt.setText("");
        mobilenotxt.setText("");
        add1txt1.setText("");
        housenotxt1.setText("");
        citytxt1.setText("");
        statetxt1.setText("");
        zipcodetxt1.setText("");
        mobilenotxt1.setText("");
    }//GEN-LAST:event_createbtnActionPerformed

    private void statetxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statetxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statetxt1ActionPerformed

    private void salarytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarytxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add1lbl;
    private javax.swing.JLabel add1lbl1;
    private javax.swing.JTextField add1txt;
    private javax.swing.JTextField add1txt1;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel citylbl;
    private javax.swing.JLabel citylbl1;
    private javax.swing.JTextField citytxt;
    private javax.swing.JTextField citytxt1;
    private javax.swing.JLabel createLabel;
    private javax.swing.JButton createbtn;
    private javax.swing.JLabel employeeidlbl;
    private javax.swing.JTextField employeeidtxt;
    private javax.swing.JLabel firstnamelbl;
    private javax.swing.JTextField firstnametxt;
    private javax.swing.JLabel genderlbl;
    private javax.swing.JTextField gendertxt;
    private javax.swing.JLabel housenolbl;
    private javax.swing.JLabel housenolbl1;
    private javax.swing.JTextField housenotxt;
    private javax.swing.JTextField housenotxt1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel landmarklbl;
    private javax.swing.JLabel landmarklbl1;
    private javax.swing.JTextField landmarktxt;
    private javax.swing.JTextField landmarktxt1;
    private javax.swing.JLabel lastnamelbl;
    private javax.swing.JTextField lastnametxt;
    private javax.swing.JLabel mobilenolbl;
    private javax.swing.JLabel mobilenolbl1;
    private javax.swing.JTextField mobilenotxt;
    private javax.swing.JTextField mobilenotxt1;
    private javax.swing.JLabel peraddlbl;
    private javax.swing.JLabel preaddlbl;
    private javax.swing.JLabel salarylbl;
    private javax.swing.JTextField salarytxt;
    private javax.swing.JLabel ssnlbl;
    private javax.swing.JTextField ssntxt;
    private javax.swing.JLabel statelbl;
    private javax.swing.JLabel statelbl1;
    private javax.swing.JTextField statetxt;
    private javax.swing.JTextField statetxt1;
    private javax.swing.JLabel zipcodelbl;
    private javax.swing.JLabel zipcodelbl1;
    private javax.swing.JTextField zipcodetxt;
    private javax.swing.JTextField zipcodetxt1;
    // End of variables declaration//GEN-END:variables

    private boolean validateInputFields() {
    
    if (firstnametxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "First Name cannot be empty.");
        return false;
    }
    if (lastnametxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Last Name cannot be empty.");
        return false;
    }
    
    if (ssntxt.getText().trim().isEmpty() || !ssntxt.getText().matches("\\d{9}")) {
        JOptionPane.showMessageDialog(this, "Social Security Number must be exactly 9 digits.");
        return false;
    }
    
    if (salarytxt.getText().trim().isEmpty() || !salarytxt.getText().matches("\\d+(\\.\\d+)?")) {
        JOptionPane.showMessageDialog(this, "Salary Field must not be empty.");
        return false;
    }
    
    if (employeeidtxt.getText().trim().isEmpty() || !employeeidtxt.getText().matches("\\d{7}")) {
        JOptionPane.showMessageDialog(this, "employee must be exactly 7 digits.");
        return false;
    }
    
    if (gendertxt.getText().trim().isEmpty() ) {
        JOptionPane.showMessageDialog(this, "Gender cannot be empty.");
        return false;
    }


    if (add1txt1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Home Address Street cannot be empty.");
        return false;
    }
    if (citytxt1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Home Address City cannot be empty.");
        return false;
    }
    if (statetxt1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Home Address State cannot be empty.");
        return false;
    }
    
    if (landmarktxt1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Work Address State cannot be empty.");
        return false;
    }
     
    if (housenotxt1.getText().trim().isEmpty() || !housenotxt1.getText().matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Work Address Zip Code must be a valid number.");
        return false;
    }
    if (zipcodetxt1.getText().trim().isEmpty() || !zipcodetxt1.getText().matches("\\d{5}")) {
        JOptionPane.showMessageDialog(this, "Home Address Zip Code must be exactly 5 digits.");
        return false;
    }
    if (mobilenotxt1.getText().trim().isEmpty() || !mobilenotxt1.getText().matches("\\d{10}")) {
        JOptionPane.showMessageDialog(this, "Home Address Phone Number must be exactly 10 digits.");
        return false;
    }


    if (add1txt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Work Address Street cannot be empty.");
        return false;
    }
    if (citytxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Work Address City cannot be empty.");
        return false;
    }
    if (statetxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Work Address State cannot be empty.");
        return false;
    }
    
    if (landmarktxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Work Address State cannot be empty.");
        return false;
    }
     
    if (housenotxt.getText().trim().isEmpty() || !housenotxt.getText().matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Work Address Zip Code must be a valid number.");
        return false;
    }
      
    if (zipcodetxt.getText().trim().isEmpty() || !zipcodetxt.getText().matches("\\d{5}")) {
        JOptionPane.showMessageDialog(this, "Work Address Zip Code must be exactly 5 digits.");
        return false;
    }
    if (mobilenotxt.getText().trim().isEmpty() || !mobilenotxt.getText().matches("\\d{10}")) {
        JOptionPane.showMessageDialog(this, "Work Address Phone Number must be exactly 10 digits.");
        return false;
    }


    return true;
}
}
