/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author DELL
 */
public class MainFrame extends javax.swing.JFrame {
    
    PersonDirectory personDirectory;
    private ViewListJPanel listPanel;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.personDirectory = new PersonDirectory();
        listPanel = new ViewListJPanel(WorkCard, personDirectory);
        
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        createtxtfield = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        searchTxtField = new javax.swing.JTextField();
        WorkCard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 51, 102));

        jButton1.setText("View  Profiles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        createtxtfield.setText("Create Person");
        createtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createtxtfieldActionPerformed(evt);
            }
        });

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createtxtfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(searchTxtField))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(createtxtfield)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(74, 74, 74)
                .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchbtn)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        WorkCard.setBackground(new java.awt.Color(102, 153, 255));
        WorkCard.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(WorkCard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createtxtfieldActionPerformed
        // TODO add your handling code here:
        CreateJPanel panel = new CreateJPanel(WorkCard, personDirectory);
        WorkCard.add("CreateJPanel",panel);
        
        CardLayout layout=(CardLayout) WorkCard.getLayout();
        layout.next(WorkCard);
    }//GEN-LAST:event_createtxtfieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        listPanel.populateTable();
        WorkCard.add("ViewListJpanel",listPanel);
        
        CardLayout layout=(CardLayout) WorkCard.getLayout();
        layout.next(WorkCard);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        String searchText = searchTxtField.getText();
        
        
        if (!searchText.isBlank()) {
        Person foundAccount = null;
        
        try {
            // Check if searchText is an integer (SSN)
            long ssn = Long.parseLong(searchText);
            foundAccount = personDirectory.searchAccount(ssn);
        } catch (NumberFormatException e) {
            // If not an integer, search by name or address
            foundAccount = personDirectory.searchAccount(searchText);
        }

        if (foundAccount != null) {
            
            ViewJPanel panel= new ViewJPanel(WorkCard,personDirectory,foundAccount,listPanel);
            WorkCard.add("ViewJPanel",panel);
        
            CardLayout layout=(CardLayout) WorkCard.getLayout();
            layout.next(WorkCard);
        } else {
            JOptionPane.showMessageDialog(null, "Account not Found. Please check and try again", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "Please enter the search text to view the person profile", "Warning", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_searchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WorkCard;
    private javax.swing.JButton createtxtfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JButton searchbtn;
    // End of variables declaration//GEN-END:variables

    private void generateDemoData() {
    // Creating the first person
    Person newPerson1 = personDirectory.addAccount();
    newPerson1.setFirstName("Rahul");
    newPerson1.setLastName("Reddy");
    newPerson1.setSsn((long)123456780);
    newPerson1.setGender("Male");
    newPerson1.setSalary((float)12345.67);
    newPerson1.setEmployeeid(1234560);

    // Set Home Address for Person 1
    newPerson1.setPrehomeAdd(new Address("Mt Pleasent avenue", "MA", "Boston","School",100, 12345,(long)1234567890));

    // Set Work Address for Person 1
    newPerson1.setPerhomeAdd(new Address("4 Elizabeth Ave", "MA", "Boston","Community center", 214, 12139, 1234567891L));

    // Creating second person
    Person newPerson2 = personDirectory.addAccount();
    newPerson2.setFirstName("Max");
    newPerson2.setLastName("Goldman");
    newPerson2.setSsn((long)123456781);
    newPerson2.setGender("Male");
    newPerson2.setSalary((float)125005.67);
    newPerson2.setEmployeeid(1234561);

    // Set Home Address for Person 2
    newPerson2.setPrehomeAdd(new Address("123 Maple Street", "California", "Los Angeles","Near Central Park",456, 90001, 9876543210L));

    // Set Work Address for Person 2
    newPerson2.setPerhomeAdd(new Address("789 Oak Avenue", "Texas",  "Austin", "Opposite City Mall",102, 73301, 9123456780L));

    // Repeat similar steps for newPerson3, newPerson4, newPerson5...

    Person newPerson3 = personDirectory.addAccount();
    newPerson3.setFirstName("Frank");
    newPerson3.setLastName("Silverman");
    newPerson3.setSsn((long)123456782);
    newPerson3.setGender("Male");
    newPerson3.setSalary((float)12550.67);
    newPerson3.setEmployeeid(1234562);

    newPerson3.setPrehomeAdd(new Address("456 Pine Drive", "New York", "Buffalo", "Next to Main Library", 789,14201, 9988776655L));
    newPerson3.setPerhomeAdd(new Address("321 Cedar Lane", "Florida", "Orlando", "Near Disney World",214, 32801, 8899001122L));

    Person newPerson4 = personDirectory.addAccount();
    newPerson4.setFirstName("Steve");
    newPerson4.setLastName("Rothsman");
    newPerson4.setSsn((long)123456783);
    newPerson4.setGender("Male");
    newPerson4.setSalary((float)12559.67);
    newPerson4.setEmployeeid(1234563);

    newPerson4.setPrehomeAdd(new Address("987 Birch Boulevard", "Illinois", "Chicago", "Beside Millenium Park",365, 60601, 7766554433L));
    newPerson4.setPerhomeAdd(new Address("654 Spruce Street", "Ohio", "Columbus", "Near Riverside Hospital",120, 43085, 9988007766L));

    Person newPerson5 = personDirectory.addAccount();
    newPerson5.setFirstName("Prince");
    newPerson5.setLastName("Newwman");
    newPerson5.setSsn((long)123456784);
    newPerson5.setGender("Male");
    newPerson5.setSalary((float)12600.67);
    newPerson5.setEmployeeid(1234564);

    newPerson5.setPrehomeAdd(new Address("876 Willow Road", "Nevada", "Las Vegas", "Close to MGM Grand",221, 89109, 8877665544L));
    newPerson5.setPerhomeAdd(new Address("543 Elm Drive", "Georgia", "Atlanta", "Adjacent to Peachtree Plaza",325, 30301, 7766443322L));
}
}
