/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author DELL
 */
public class ViewJPanel extends javax.swing.JPanel {
    
    
        
    JPanel WorkCard;
    PersonDirectory personDirectory;
    Person person;
    ViewListJPanel listPanel;

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(JPanel WorkCard,PersonDirectory personDirectory, Person p, ViewListJPanel listPanel) {
        initComponents();
        
        this.WorkCard=WorkCard;
        this.personDirectory=personDirectory;
        person=p;
        this.listPanel=listPanel;
        
            refreshTextFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbtn = new javax.swing.JButton();
        viewLabel = new javax.swing.JLabel();
        firstnametxt = new javax.swing.JTextField();
        firstnamelbl = new javax.swing.JLabel();
        ssnlbl = new javax.swing.JLabel();
        ssntxt = new javax.swing.JTextField();
        genderlbl = new javax.swing.JLabel();
        gendertxt = new javax.swing.JTextField();
        lastnametxt = new javax.swing.JTextField();
        lastnamelbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        preaddlbl = new javax.swing.JLabel();
        add1lbl = new javax.swing.JLabel();
        add1txt = new javax.swing.JTextField();
        statetxt = new javax.swing.JTextField();
        statelbl = new javax.swing.JLabel();
        housenolbl = new javax.swing.JLabel();
        housenotxt = new javax.swing.JTextField();
        zipcodetxt = new javax.swing.JTextField();
        zipcodelbl = new javax.swing.JLabel();
        mobilenotxt = new javax.swing.JTextField();
        mobilenolbl = new javax.swing.JLabel();
        citytxt = new javax.swing.JTextField();
        landmarklbl = new javax.swing.JLabel();
        landmarktxt = new javax.swing.JTextField();
        citylbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        peraddlbl = new javax.swing.JLabel();
        add1lbl1 = new javax.swing.JLabel();
        mobilenotxt1 = new javax.swing.JTextField();
        statetxt1 = new javax.swing.JTextField();
        zipcodelbl1 = new javax.swing.JLabel();
        mobilenolbl1 = new javax.swing.JLabel();
        zipcodetxt1 = new javax.swing.JTextField();
        statelbl1 = new javax.swing.JLabel();
        add1txt1 = new javax.swing.JTextField();
        housenotxt1 = new javax.swing.JTextField();
        citytxt1 = new javax.swing.JTextField();
        citylbl1 = new javax.swing.JLabel();
        housenolbl1 = new javax.swing.JLabel();
        landmarktxt1 = new javax.swing.JTextField();
        landmarklbl1 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        salarylbl = new javax.swing.JLabel();
        salarytxt = new javax.swing.JTextField();
        employeeidlbl = new javax.swing.JLabel();
        employeeidtxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 255));

        backbtn.setText("<<< Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        viewLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        viewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewLabel.setText("View Profile");

        firstnamelbl.setText("First Name");

        ssnlbl.setText("SSN");

        genderlbl.setText("Gender");

        lastnamelbl.setText("Last Name");

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));

        preaddlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        preaddlbl.setText("Present Address");

        add1lbl.setText("Address");

        statelbl.setText("State");

        housenolbl.setText("House No.");

        zipcodelbl.setText("ZipCode");

        mobilenolbl.setText("Mobile No.");

        landmarklbl.setText("Landmark");

        citylbl.setText("City");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(add1lbl)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(preaddlbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(add1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(housenolbl)
                            .addComponent(statelbl)
                            .addComponent(landmarklbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(statetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zipcodelbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(landmarktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mobilenolbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(housenotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(citylbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(citytxt)
                            .addComponent(zipcodetxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobilenotxt, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(preaddlbl)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add1lbl)
                    .addComponent(add1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housenolbl)
                    .addComponent(housenotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(citytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(citylbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statelbl)
                    .addComponent(statetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcodelbl)
                    .addComponent(zipcodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(landmarklbl)
                    .addComponent(landmarktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobilenolbl)
                    .addComponent(mobilenotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));

        peraddlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        peraddlbl.setText("Permanent Address");

        add1lbl1.setText("Address 1");

        statetxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statetxt1ActionPerformed(evt);
            }
        });

        zipcodelbl1.setText("ZipCode");

        mobilenolbl1.setText("Mobile No.");

        statelbl1.setText("State");

        citytxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citytxt1ActionPerformed(evt);
            }
        });

        citylbl1.setText("City");

        housenolbl1.setText("House No.");

        landmarklbl1.setText("Landmark");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(peraddlbl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(add1lbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(add1txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(housenolbl1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(housenotxt1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(landmarklbl1)
                                        .addGap(18, 18, 18)
                                        .addComponent(landmarktxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(statelbl1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(statetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(mobilenolbl1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mobilenotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(zipcodelbl1)
                                            .addComponent(citylbl1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(citytxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(zipcodetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {citytxt1, mobilenotxt1, zipcodetxt1});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {housenotxt1, landmarktxt1, statetxt1});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(peraddlbl)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add1lbl1)
                    .addComponent(add1txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housenolbl1)
                    .addComponent(housenotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(citytxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(citylbl1))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statelbl1)
                    .addComponent(zipcodelbl1)
                    .addComponent(zipcodetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilenotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobilenolbl1)
                    .addComponent(landmarklbl1)
                    .addComponent(landmarktxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        salarylbl.setText("Salary");

        employeeidlbl.setText("Employee Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(salarylbl)
                        .addGap(35, 35, 35)
                        .addComponent(salarytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239)
                        .addComponent(employeeidlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeeidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backbtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(viewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ssnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ssntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(firstnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(firstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(234, 234, 234)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lastnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lastnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(genderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(gendertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salarylbl)
                    .addComponent(salarytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeidlbl)
                    .addComponent(employeeidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updatebtn)
                .addGap(14, 14, 14))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewLabel))
                    .addGap(52, 52, 52)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstnamelbl)
                        .addComponent(firstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastnamelbl)
                        .addComponent(lastnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(52, 52, 52)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(genderlbl)
                        .addComponent(gendertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ssnlbl)
                        .addComponent(ssntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(424, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        
        listPanel.populateTable();
        WorkCard.remove(this);
        CardLayout layout = (CardLayout) WorkCard.getLayout();
        layout.previous(WorkCard);

    }//GEN-LAST:event_backbtnActionPerformed

    private void statetxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statetxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statetxt1ActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
            if (validateFields()) {
        // Update the person object with new values from form fields
        person.setFirstName(firstnametxt.getText());
        person.setLastName(lastnametxt.getText());
        person.setGender(gendertxt.getText());
        person.setSsn(Long.parseLong(ssntxt.getText()));
        person.setSalary(Float.parseFloat(salarytxt.getText()));
        person.setEmployeeid(Integer.parseInt(employeeidtxt.getText()));

        // Update Home Address
        if (person.getPerhomeAdd()!= null) {
            person.getPerhomeAdd().setStadd1(add1txt.getText());
            person.getPerhomeAdd().setHouseno(Integer.parseInt(housenotxt.getText()));
            person.getPerhomeAdd().setCity(citytxt.getText());
            person.getPerhomeAdd().setState(statetxt.getText());
            person.getPerhomeAdd().setZipcode(Integer.parseInt(zipcodetxt.getText()));
            person.getPerhomeAdd().setMobileno(Long.parseLong(mobilenotxt.getText()));
        }

        // Update Work Address
        if (person.getPrehomeAdd()!= null) {
            person.getPrehomeAdd().setStadd1(add1txt1.getText());
            person.getPrehomeAdd().setHouseno(Integer.parseInt(housenotxt1.getText()));
            person.getPrehomeAdd().setCity(citytxt1.getText());
            person.getPrehomeAdd().setState(statetxt1.getText());
            person.getPrehomeAdd().setZipcode(Integer.parseInt(zipcodetxt1.getText()));
            person.getPrehomeAdd().setMobileno(Long.parseLong(mobilenotxt1.getText()));
        }

        // Optionally: Show a message dialog to inform the user that the update was successful
        JOptionPane.showMessageDialog(this, "Profile updated successfully!");
        listPanel.populateTable();
    } else {
        // Show an error message if validation fails
        JOptionPane.showMessageDialog(this, "Please check your input fields!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void citytxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citytxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citytxt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add1lbl;
    private javax.swing.JLabel add1lbl1;
    private javax.swing.JTextField add1txt;
    private javax.swing.JTextField add1txt1;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel citylbl;
    private javax.swing.JLabel citylbl1;
    private javax.swing.JTextField citytxt;
    private javax.swing.JTextField citytxt1;
    private javax.swing.JLabel employeeidlbl;
    private javax.swing.JTextField employeeidtxt;
    private javax.swing.JLabel firstnamelbl;
    private javax.swing.JTextField firstnametxt;
    private javax.swing.JLabel genderlbl;
    private javax.swing.JTextField gendertxt;
    private javax.swing.JLabel housenolbl;
    private javax.swing.JLabel housenolbl1;
    private javax.swing.JTextField housenotxt;
    private javax.swing.JTextField housenotxt1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel landmarklbl;
    private javax.swing.JLabel landmarklbl1;
    private javax.swing.JTextField landmarktxt;
    private javax.swing.JTextField landmarktxt1;
    private javax.swing.JLabel lastnamelbl;
    private javax.swing.JTextField lastnametxt;
    private javax.swing.JLabel mobilenolbl;
    private javax.swing.JLabel mobilenolbl1;
    private javax.swing.JTextField mobilenotxt;
    private javax.swing.JTextField mobilenotxt1;
    private javax.swing.JLabel peraddlbl;
    private javax.swing.JLabel preaddlbl;
    private javax.swing.JLabel salarylbl;
    private javax.swing.JTextField salarytxt;
    private javax.swing.JLabel ssnlbl;
    private javax.swing.JTextField ssntxt;
    private javax.swing.JLabel statelbl;
    private javax.swing.JLabel statelbl1;
    private javax.swing.JTextField statetxt;
    private javax.swing.JTextField statetxt1;
    private javax.swing.JButton updatebtn;
    private javax.swing.JLabel viewLabel;
    private javax.swing.JLabel zipcodelbl;
    private javax.swing.JLabel zipcodelbl1;
    private javax.swing.JTextField zipcodetxt;
    private javax.swing.JTextField zipcodetxt1;
    // End of variables declaration//GEN-END:variables
    
    private boolean validateFields() {
    // Validate basic details
    
    if (firstnametxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "First Name cannot be empty.");
        return false;
    }
    if (lastnametxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Last Name cannot be empty.");
        return false;
    }
    
    if (gendertxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Gendewr cannot be empty.");
        return false;
    }
    
    if (ssntxt.getText().trim().isEmpty() || !ssntxt.getText().matches("\\d{9}")) {
        JOptionPane.showMessageDialog(this, "Social Security Number must be exactly 9 digits.");
        return false;
    }
    
    if (salarytxt.getText().trim().isEmpty() || !salarytxt.getText().matches("\\d+(\\.\\d+)?")) {
        JOptionPane.showMessageDialog(this, "Salary Field must not be empty.");
        return false;
    }
    
    if (employeeidtxt.getText().trim().isEmpty() || !employeeidtxt.getText().matches("\\d{7}")) {
        JOptionPane.showMessageDialog(this, "Social Security Number must be exactly 7 digits.");
        return false;
    }
    
    if (housenotxt.getText().trim().isEmpty() || !housenotxt.getText().matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "House No. must be a valid number.");
        return false;
    }
    
     if (housenotxt1.getText().trim().isEmpty() || !housenotxt1.getText().matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "House No. must be a valid number.");
        return false;
    }
    
    if (citytxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "City field cannot be empty.");
        return false;
    }
    
     if (citytxt1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "City field cannot be empty.");
        return false;
    }
    
    if (statetxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "State field cannot be empty.");
        return false;
    }
    
      if (statetxt1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "State field cannot be empty.");
        return false;
    }


    if (add1txt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Address Street cannot be empty.");
        return false;
    }
    if (landmarktxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Landmark Field cannot be empty.");
        return false;
    }
    if (zipcodetxt.getText().trim().isEmpty() || !zipcodetxt.getText().matches("\\d{5}")) {
        JOptionPane.showMessageDialog(this, "Home Address Zip Code must be exactly 5 digits.");
        return false;
    }
    
    if (mobilenotxt.getText().trim().isEmpty() || !mobilenotxt.getText().matches("\\d{10}")) {
       JOptionPane.showMessageDialog(this, "Present Address Mobile No must be exactly 10 digits.");
       return false;
        }
    if (add1txt1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Address Street cannot be empty.");
        return false;
    }
    if (landmarktxt1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Landmark cannot be empty.");
        return false;
    }
 
    if (zipcodetxt1.getText().trim().isEmpty() || !zipcodetxt1.getText().matches("\\d{5}")) {
        JOptionPane.showMessageDialog(this, "Zip Code must be exactly 5 digits.");
        return false;
    }
    if (mobilenotxt1.getText().trim().isEmpty() || !mobilenotxt1.getText().matches("\\d{10}")) {
        JOptionPane.showMessageDialog(this, "Permanent Address Mobile Number must be exactly 10 digits.");
        return false;
    }

    // All fields are valid
    return true;
}
    
    private void refreshTextFields() {
    firstnametxt.setText(person.getFirstName());
    lastnametxt.setText(person.getLastName());
    ssntxt.setText(String.valueOf(person.getSsn())); 
    gendertxt.setText(person.getGender()); 
    employeeidtxt.setText(String.valueOf(person.getEmployeeid()));
    salarytxt.setText(String.valueOf(person.getSalary()));

    
    if (person.getPerhomeAdd()!= null) {
        add1txt.setText(person.getPerhomeAdd().getStadd1());
        housenotxt.setText(String.valueOf(person.getPerhomeAdd().getHouseno()));
        citytxt.setText(person.getPerhomeAdd().getCity());
        statetxt.setText(person.getPerhomeAdd().getState());
        landmarktxt.setText(person.getPerhomeAdd().getLandmark());
        zipcodetxt.setText(String.valueOf(person.getPerhomeAdd().getZipcode()));
        mobilenotxt.setText(String.valueOf(person.getPerhomeAdd().getMobileno()));
    }

    if (person.getPrehomeAdd()!= null) {
        add1txt1.setText(person.getPrehomeAdd().getStadd1());
        housenotxt1.setText(String.valueOf(person.getPrehomeAdd().getHouseno()));
        citytxt1.setText(person.getPrehomeAdd().getCity());
        statetxt1.setText(person.getPrehomeAdd().getState());
        landmarktxt1.setText(person.getPrehomeAdd().getLandmark());
        zipcodetxt1.setText(String.valueOf(person.getPrehomeAdd().getZipcode()));
        mobilenotxt1.setText(String.valueOf(person.getPrehomeAdd().getMobileno()));
    }
}
}
