/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProfileManager;

import Model.HomeAddress;
import Model.Person;
import Model.PersonDirectory;
import Model.WorkAddress;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Satwika
 */
public class ListJPanel extends javax.swing.JPanel {
    JPanel Area;
    PersonDirectory personDirectory;
    /**
     * Creates new form ListJPanel
     */
    public ListJPanel(JPanel container, PersonDirectory directory) {
        initComponents();
        
        Area = container;
        personDirectory = directory;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetails = new javax.swing.JTable();
        BtnSearchName = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearchName = new javax.swing.JTextField();
        txtSearchAddress = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List of People");

        tblDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Home Address", "Work Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDetails);

        BtnSearchName.setText("Search by Name");
        BtnSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchNameActionPerformed(evt);
            }
        });

        jButton2.setText("Search by Address");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("View details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(BtnSearchName)
                    .addComponent(btnDelete))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearchName)
                    .addComponent(txtSearchAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnSearchName, btnDelete, jButton2, jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSearchName)
                    .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(txtSearchAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDetails.getSelectedRow();
      
        if (selectedRow >= 0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected person details?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION){
                Person selectedPerson = (Person) tblDetails.getValueAt(selectedRow, 0);
                personDirectory.deletePerson(selectedPerson);
                populateTable();
            
            }
            }else{
                JOptionPane.showMessageDialog(null, "Please select an person from the list.", "Warning", JOptionPane.WARNING_MESSAGE);
                
        }
     
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void BtnSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchNameActionPerformed
        // TODO add your handling code here:
        if(!txtSearchName.getText().isBlank()){
            String FirstName = txtSearchName.getText();
            Person foundPerson = personDirectory.searchperson(FirstName);
            
            if(foundPerson != null){
                ViewJPanel panel = new ViewJPanel(Area, personDirectory, foundPerson);
                Area.add("ViewJPanel",panel);
                CardLayout layout = (CardLayout) Area.getLayout();
                layout.next(Area);
            }else {
                JOptionPane.showMessageDialog(null, "Person not found. Please check the firstname and try again", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please type the person firstname to view", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_BtnSearchNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!txtSearchAddress.getText().isBlank()){
            String CurrentAddress = txtSearchName.getText();
            Person foundAddress = personDirectory.searchaddress(CurrentAddress);
            
            if(foundAddress != null){
                ViewJPanel panel = new ViewJPanel(Area, personDirectory, foundAddress);
                Area.add("ViewJPanel",panel);
                CardLayout layout = (CardLayout) Area.getLayout();
                layout.next(Area);
            }else {
                JOptionPane.showMessageDialog(null, "Person not found. Please check the Address and try again", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please type the person Address to view", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDetails.getSelectedRow();
        
        if (selectedRow >= 0){
            Person selectedPerson = (Person) tblDetails.getValueAt(selectedRow, 0);
            
            ViewJPanel panel = new ViewJPanel(Area, personDirectory, selectedPerson);
            Area.add("ViewAccountJPanel", panel);
            CardLayout layout = (CardLayout) Area.getLayout();
            layout.next(Area);
        } else{
            JOptionPane.showMessageDialog(null,"Please select a person from the list to view.", "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSearchName;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetails;
    private javax.swing.JTextField txtSearchAddress;
    private javax.swing.JTextField txtSearchName;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblDetails.getModel();
        model.setRowCount(0);
        
        for (Person p : personDirectory.getPerson()){
        
               Object[] row = new Object[4];
               row[0] = p;
               row[1] = p.getLastName();
               row[2] = p.getCurrentAddress();
               row[3] = p.getAddress();
               
               model.addRow(row);
        }
    }
}
